### ISSUE TITLE
Cholesky decomposition problem

### ISSUE THREAD

**Issue by jerryhkucs** [tnakae/DAGMM#21]
When replacing KDDCUP 10 PERCENT dataset with other datasets, always report the error message: 
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
How to fix it?

**Comment by tnakae** [comment]
@jerryhkucs 
I don't determine why Cholesky decomposition was failed because I don't have enough information about your data, but I think you have to tune training parameters adequately for your data. There are many possibilities, for example:
1. Training data in one mini-batch is too correlated. If so, mini-batch size should be increased.
2. Compression network is too shallow for your training data. If so, number of nodes / layers of the compression network should be increased.

**Comment by jerryhkucs** [comment]
Thank you very much for your reply.
